[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = true

# Security and caching (basic)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
