# Add this to the top of your existing config.yml
local_backend: true
display_url: https://nexcey.com
logo_url: /images/logo.png

# Add custom CSS
editor:
  preview: true
  
# Custom styling
styles: |
  .css-1kgqfgb-SidebarContainer {
    background: #2c3e50 !important;
  }
  .css-1hwfws3 {
    background: #522cb5 !important;
  }
  .css-1c5lpg2-AppHeaderButton {
    background: #522cb5 !important;
  }
  .css-1m0o5z5-Card {
    border-radius: 10px !important;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1) !important;
  }
backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Website Settings"
    files:
      - name: "general"
        label: "General Settings"
        file: "_data/settings.json"
        fields:
          - { label: "Site Title", name: "site_title", widget: "string", default: "Nexcey - Your Web Design Partner" }
          - { label: "Primary Color", name: "primary_color", widget: "color", default: "#522cb5" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Favicon", name: "favicon", widget: "image", required: false }

      - name: "hero"
        label: "Hero Section"
        file: "_data/hero.json"
        fields:
          - { label: "Main Title", name: "title", widget: "string", default: "Web Design that Drives Results" }
          - { label: "Subtitle", name: "subtitle", widget: "text", default: "Modern, responsive websites tailored to your brand." }
          - { label: "Call to Action Text", name: "cta_text", widget: "string", default: "Get Started" }
          - { label: "Background Image", name: "background_image", widget: "image", required: false }

      - name: "about"
        label: "About Section"
        file: "_data/about.json"
        fields:
          - { label: "Section Title", name: "title", widget: "string", default: "About Nexcey" }
          - { label: "About Text", name: "text", widget: "text", default: "Nexcey is a modern web design studio offering tailor-made website solutions. From stunning landing pages to powerful e-commerce sites, we bring your ideas to life with clean, functional, and engaging designs." }
          - { label: "About Image", name: "image", widget: "image", required: false }

      - name: "contact"
        label: "Contact Information"
        file: "_data/contact.json"
        fields:
          - { label: "Email", name: "email", widget: "string", default: "info@nexcey.com" }
          - { label: "Phone", name: "phone", widget: "string", default: "+94 72 445 2222" }
          - { label: "Address", name: "address", widget: "text", default: "203, Somananda MW, Udahamulla, Panadura, Sri Lanka" }

      - name: "social"
        label: "Social Media Links"
        file: "_data/social.json"
        fields:
          - { label: "Facebook URL", name: "facebook", widget: "string", required: false }
          - { label: "X (Twitter) URL", name: "twitter", widget: "string", required: false }
          - { label: "LinkedIn URL", name: "linkedin", widget: "string", required: false }
          - { label: "Instagram URL", name: "instagram", widget: "string", required: false }
          - { label: "WhatsApp URL", name: "whatsapp", widget: "string", required: false }

  - name: "services"
    label: "Services"
    folder: "_data/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Service Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Icon", name: "icon", widget: "select", options: ["fas fa-laptop-code", "fas fa-briefcase", "fas fa-building", "fas fa-shopping-cart", "fas fa-mobile-alt", "fas fa-paint-brush"], default: "fas fa-laptop-code" }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "pricing"
    label: "Pricing Plans"
    folder: "_data/pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Plan Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Featured Plan", name: "featured", widget: "boolean", default: false }
      - { label: "Features", name: "features", widget: "list", field: { label: "Feature", name: "feature", widget: "string" } }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "clients"
    label: "Clients"
    folder: "_data/clients"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Client Logo", name: "logo", widget: "image" }
      - { label: "Website Screenshot", name: "website_image", widget: "image" }
      - { label: "Website URL", name: "website_url", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", default: 1 }

  - name: "testimonials"
    label: "Testimonials"
    folder: "_data/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Client Photo", name: "photo", widget: "image" }
      - { label: "Testimonial", name: "comment", widget: "text" }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Order", name: "order", widget: "number", default: 1 }
