backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

site_url: "https://nexcey.com"
display_url: "https://nexcey.com"

collections:
  - name: "hero"
    label: "Hero Section"
    folder: "content/hero"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "button_text", label: "Button Text", widget: "string" }
      - { name: "button_link", label: "Button Link", widget: "string" }
      - { name: "background_image", label: "Background Image", widget: "image" }

  - name: "about"
    label: "About Section"
    folder: "content/about"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "heading", label: "Heading", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "icon", label: "Icon (SVG or Image)", widget: "image" }

  - name: "pricing"
    label: "Pricing Plans"
    folder: "content/pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "plan", label: "Plan Name", widget: "string" }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "features", label: "Features", widget: "list" }
      - { name: "button_text", label: "Button Text", widget: "string" }
      - { name: "button_link", label: "Button Link", widget: "string" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "project_name", label: "Project Name", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "link", label: "Project Link", widget: "string", required: false }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "author", label: "Name", widget: "string" }
      - { name: "role", label: "Role/Company", widget: "string" }
      - { name: "quote", label: "Testimonial", widget: "text" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "contact"
    label: "Contact Info"
    folder: "content/contact"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "address", label: "Address", widget: "string" }
      - { name: "phone", label: "Phone", widget: "string" }
      - { name: "email", label: "Email", widget: "string" }
