backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "content/homepage.yml"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Button Text", name: "hero_button", widget: "string" }

  - name: "about"
    label: "About"
    files:
      - file: "content/about.yml"
        label: "About Section"
        name: "about"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Body", name: "body", widget: "text" }

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Icon", name: "icon", widget: "image" }

  - name: "pricing"
    label: "Pricing Plans"
    folder: "content/pricing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Plan Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Features", name: "features", widget: "list" }

  - name: "clients"
    label: "Clients"
    folder: "content/clients"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Logo", name: "logo", widget: "image" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Message", name: "message", widget: "text" }
      - { label: "Photo", name: "photo", widget: "image" }

  - name: "contact"
    label: "Contact"
    files:
      - file: "content/contact.yml"
        label: "Contact Section"
        name: "contact"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Subheading", name: "subheading", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
